version: '3.5'

services:
  api01: &api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    container_name: api-plooral-01
    hostname: api01
    environment:
      - PORT=3030
      - DB_DIALECT=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=lexart-db
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  api02:
    <<: *api
    hostname: api02
    container_name: api-plooral-02
    environment:
      - PORT=3030
      - DB_DIALECT=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=lexart-db
    ports:
      - "3031:3030"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    restart: always

  # redis:
  #   image: 'redis'
  #   container_name: 'redis-plooral'
  #   ports:
  #     - '6379:6379'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes

networks:
  default:
    driver: bridge
    name: plooral-nginx