version: '3.5'

services:
  api01: &api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    container_name: api-lexart-01
    hostname: api01
    environment:
      - PORT=3030
      - DB_DIALECT=postgres
      - DB_HOST=ep-sweet-pine-a4s8bzzs-pooler.us-east-1.aws.neon.tech
      - DB_PORT=5432
      - DB_USERNAME=default
      - DB_PASSWORD=kbSDPhw1CL4a
      - DB_NAME=verceldb
      - TZ=America/Sao_Paulo
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  api02:
    <<: *api
    hostname: api02
    container_name: api-lexart-02
    ports:
      - "3031:3030"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    restart: always

  # redis:
  #   image: 'redis'
  #   container_name: 'redis-lexart'
  #   ports:
  #     - '6379:6379'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes

networks:
  default:
    driver: bridge
    name: lexart-nginx